on:
  schedule:
    - cron: '41 18 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
    build-and-publish:
      runs-on: ubuntu-latest
      name: My workflow
      steps:
        - name: Execute Action Graph
          uses: actionforge/action@dd84b97bb5d3a0f17bda0ce7d20ffa96e3bd8f1c # v0.15.4
          with:
            graph_file: new-1.yml